# Generated by Django 4.1.13 on 2024-05-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.topic'),
        ),
    ]
