# Generated by Django 4.1.13 on 2024-05-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
